version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tarafirst
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/docker_deploy.sh
      timeout: 300
      runas: ubuntu



