version: 0.2

cache:
  paths:
    - '/root/.cache/pip/**/*'  # Cache pip dependencies

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - |
        # Check if requirements.txt has changed; install dependencies only if it has.
        if ! cmp -s requirements.txt /tmp/previous_requirements.txt; then
          echo "Requirements changed, installing dependencies..."
          pip3 install -r requirements.txt
          cp requirements.txt /tmp/previous_requirements.txt  # Cache the requirements.txt for comparison in the next build
        else
          echo "No changes in requirements, skipping install."
        fi

  build:
    commands:
      - echo Building the application
      - |
        # Check if static files already exist and have not changed
        if [ ! -d "staticfiles" ] || [ "$(find staticfiles -type f | wc -l)" -eq "0" ]; then
          echo "Static files not found or empty, running collectstatic..."
          python3 manage.py collectstatic --noinput
        else
          echo "Static files already collected, skipping collectstatic."
        fi

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'
