version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies using multiple jobs"
      - pip install -r requirements.txt -j 8  # Install dependencies with 8 parallel jobs

  build:
    commands:
      - echo "Running the build steps"
      - python manage.py collectstatic --noinput  # Other build steps if necessary

  post_build:
    commands:
      - echo "Build completed"
