version: 0.2

phases:
  install:
    commands:
      - echo "Setting up virtual environment"
      - cd /home/ubuntu/TaraFirst  # Navigate to the directory containing manage.py and requirements.txt
      # Check if virtual environment exists before creating it
      - if [ ! -d "/home/ubuntu/TaraFirst/venv" ]; then python3 -m venv /home/ubuntu/TaraFirst/venv; fi  # Create venv if it doesn't exist
      - source /home/ubuntu/TaraFirst/venv/bin/activate  # Activate the virtual environment
      - pip install -r requirements.txt  # Install dependencies
  build:
    commands:
      - echo "Running the build steps"
      - python manage.py collectstatic --noinput  # Or other build commands if needed
  post_build:
    commands:
      - echo "Build completed"
