version: 0.2

cache:
  paths:
    - '/root/.cache/pip/**/*'  # Cache pip dependencies
    - 'staticfiles/**/*'       # Cache collected static files
    - '/tmp/previous_*'        # Cache previous checksums for comparison

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - |
        # Check if requirements.txt has changed
        if ! cmp -s <(sha256sum requirements.txt) <(sha256sum /tmp/previous_requirements.txt); then
          echo "Requirements changed, installing dependencies..."
          pip3 install --cache-dir=/root/.cache/pip -r requirements.txt
          sha256sum requirements.txt > /tmp/previous_requirements.txt  # Save the hash of requirements.txt
        else
          echo "No changes in requirements.txt, skipping dependency installation."
        fi

  build:
    commands:
      - echo "Starting build phase..."
      - |
        # Skip collectstatic if static files have not changed
        if [ ! -f "staticfiles/staticfiles.json" ] || ! cmp -s staticfiles/staticfiles.json /tmp/previous_staticfiles.json; then
          echo "Static files changed, running collectstatic..."
          python3 manage.py collectstatic --noinput
          cp staticfiles/staticfiles.json /tmp/previous_staticfiles.json  # Save the manifest for comparison
        else
          echo "No changes in static files, skipping collectstatic."
        fi

  post_build:
    commands:
      - echo "Post-build phase completed on $(date)"

artifacts:
  files:
    - '**/*'  # Include all files in the build artifacts
