version: '3.8'

services:
  backend:
    image: ${DOCKER_IMAGE}:${IMAGE_TAG}
    container_name: tara_backend_dev
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - backend_logs:/app/logs
    command: >
      gunicorn Tara.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2
      --access-logfile /app/logs/access.log
      --error-logfile /app/logs/error.log
    networks:
      - taranet

volumes:
  backend_logs:

networks:
  taranet:
    driver: bridge
