# Generated by Django 5.0.4 on 2025-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_alter_employeemanagement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
